app = "panicroom"
primary_region = "ord"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"
  DATABASE_URL = "postgres://u5tft6nt3l02pu:pde6d2a6076a633f3e340eb9bb471f57fa7de6b4d6170dc417e2ba85c74def9ed@ceqbglof0h8enj.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d1dhe57i9s90i8"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"