# Generated by Django 4.2.2 on 2023-06-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_fear_name_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fear',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='photo',
            name='fear',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.fear'),
        ),
    ]
